name: 'Load Versions'
description: 'Loads version numbers from centralized versions.yml file'
author: 'Tyler Dukes'

outputs:
  # Runtime versions
  python-version:
    description: 'Python runtime version'
    value: ${{ steps.load.outputs.python-version }}
  node-version:
    description: 'Node.js runtime version'
    value: ${{ steps.load.outputs.node-version }}

  # GitHub Actions versions
  checkout-version:
    description: 'actions/checkout version'
    value: ${{ steps.load.outputs.checkout-version }}
  setup-python-version:
    description: 'actions/setup-python version'
    value: ${{ steps.load.outputs.setup-python-version }}
  setup-node-version:
    description: 'actions/setup-node version'
    value: ${{ steps.load.outputs.setup-node-version }}
  cache-version:
    description: 'actions/cache version'
    value: ${{ steps.load.outputs.cache-version }}
  upload-artifact-version:
    description: 'actions/upload-artifact version'
    value: ${{ steps.load.outputs.upload-artifact-version }}
  github-script-version:
    description: 'actions/github-script version'
    value: ${{ steps.load.outputs.github-script-version }}

  # Third-party actions
  setup-uv-version:
    description: 'astral-sh/setup-uv version'
    value: ${{ steps.load.outputs.setup-uv-version }}
  docker-setup-buildx-version:
    description: 'docker/setup-buildx-action version'
    value: ${{ steps.load.outputs.docker-setup-buildx-version }}
  docker-login-version:
    description: 'docker/login-action version'
    value: ${{ steps.load.outputs.docker-login-version }}
  docker-metadata-version:
    description: 'docker/metadata-action version'
    value: ${{ steps.load.outputs.docker-metadata-version }}
  docker-build-push-version:
    description: 'docker/build-push-action version'
    value: ${{ steps.load.outputs.docker-build-push-version }}
  anchore-sbom-version:
    description: 'anchore/sbom-action version'
    value: ${{ steps.load.outputs.anchore-sbom-version }}
  markdown-link-check-version:
    description: 'gaurav-nelson/github-action-markdown-link-check version'
    value: ${{ steps.load.outputs.markdown-link-check-version }}

  # Tool URLs
  uv-install-script:
    description: 'UV installation script URL'
    value: ${{ steps.load.outputs.uv-install-script }}

runs:
  using: 'composite'
  steps:
    - name: Load version numbers from versions.yml
      id: load
      shell: bash
      run: |
        # Install yq if not available
        if ! command -v yq &> /dev/null; then
          echo "Installing yq..."
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        fi

        VERSIONS_FILE="${{ github.workspace }}/.github/versions.yml"

        if [ ! -f "$VERSIONS_FILE" ]; then
          echo "::error::versions.yml not found at $VERSIONS_FILE"
          exit 1
        fi

        echo "Loading versions from $VERSIONS_FILE"

        # Load runtime versions
        echo "python-version=$(yq '.runtimes.python' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "node-version=$(yq '.runtimes.node' $VERSIONS_FILE)" >> $GITHUB_OUTPUT

        # Load GitHub Actions versions
        echo "checkout-version=$(yq '.actions.checkout' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "setup-python-version=$(yq '.actions.setup-python' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "setup-node-version=$(yq '.actions.setup-node' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "cache-version=$(yq '.actions.cache' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "upload-artifact-version=$(yq '.actions.upload-artifact' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "github-script-version=$(yq '.actions.github-script' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "setup-uv-version=$(yq '.actions.astral-sh-setup-uv' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "docker-setup-buildx-version=$(yq '.actions.docker-setup-buildx' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "docker-login-version=$(yq '.actions.docker-login' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "docker-metadata-version=$(yq '.actions.docker-metadata' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "docker-build-push-version=$(yq '.actions.docker-build-push' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "anchore-sbom-version=$(yq '.actions.anchore-sbom' $VERSIONS_FILE)" >> $GITHUB_OUTPUT
        echo "markdown-link-check-version=$(yq '.actions.markdown-link-check' $VERSIONS_FILE)" >> $GITHUB_OUTPUT

        # Load tool URLs
        echo "uv-install-script=$(yq '.tools.uv_install_script' $VERSIONS_FILE)" >> $GITHUB_OUTPUT

        echo "✅ All versions loaded successfully"
