# Centralized Version Management
# Single source of truth for all GitHub Actions workflows
#
# This file contains all version numbers used across workflows to simplify
# dependency management and ensure consistency.

# Language runtime versions
runtimes:
  python: '3.11'
  node: '20'

# GitHub Actions versions
actions:
  # Core actions
  checkout: 'v6.0.1'
  setup-python: 'v6.1.0'
  setup-node: 'v6'
  cache: 'v5'
  upload-artifact: 'v6'
  github-script: 'v8'

  # Third-party actions
  astral-sh-setup-uv: 'v7.1.6'
  docker-setup-buildx: 'v3'
  docker-login: 'v3'
  docker-metadata: 'v5'
  docker-build-push: 'v6'
  anchore-sbom: 'v0'
  markdown-link-check: 'v1'

# Tool installation URLs
tools:
  uv_install_script: 'https://astral.sh/uv/install.sh'
