#!/usr/bin/env python3
"""
Create individual GitHub issues for each new language release.

@module create_release_issues
@description Creates GitHub issues with comprehensive update checklists
@version 1.0.0
@author Tyler Dukes
@last_updated 2025-01-03
@status stable
"""

import os
import sys
import json
import requests
from typing import Dict, Any


def create_issue(
    language_data: Dict[str, Any], repo_owner: str, repo_name: str
) -> Dict[str, Any]:
    """Create GitHub issue for language release."""

    lang_title = language_data["language"].replace("-", " ").replace("_", " ").title()

    title = f"[LANGUAGE UPDATE] {lang_title} {language_data['latest_version']} Released"

    body = f"""## Language Release Notification

A new version of **{lang_title}** has been released!

### Version Information

- **Current documented version**: {language_data['current_version']}
- **Latest available version**: {language_data['latest_version']}
- **EOL date** (if known): {language_data.get('eol_date', 'N/A')}
- **Release date**: {language_data.get('release_date', 'N/A')}
- **Guide location**: `{language_data['guide_path']}`

### Update Checklist

Complete these tasks to update the style guide for this language release:

#### Documentation Updates
- [ ] Update version reference in `{language_data['guide_path']}`
- [ ] Update "Supported Versions" section with version range
- [ ] Add EOL date to documentation: {language_data.get('eol_date', 'TBD')}
- [ ] Review new language features and update examples if relevant
- [ ] Check for deprecated features and add warnings
- [ ] Update minimum version requirements if applicable

#### Code Examples
- [ ] Test all code examples against new version
- [ ] Update examples to use new language features (if beneficial)
- [ ] Add migration notes for breaking changes (if any)
- [ ] Ensure 3:1 code-to-text ratio maintained
- [ ] Verify all syntax highlighting works correctly

#### Tooling Updates
- [ ] Update IDE settings (`.vscode/settings.json`, `.idea/`)
- [ ] Update linter/formatter configurations
- [ ] Update pre-commit hooks if version-specific
- [ ] Test validation scripts against new version
- [ ] Update language server configurations

#### CI/CD
- [ ] Update Docker base image version (if applicable)
- [ ] Update GitHub Actions version matrices (if applicable)
- [ ] Update `.github/versions.yml` with new version
- [ ] Test full CI pipeline with new version
- [ ] Verify all workflows pass with new version

#### Templates & Examples
- [ ] Update `docs/04_templates/` with new version info
- [ ] Refresh `docs/05_examples/` implementations
- [ ] Update anti-patterns if new ones introduced
- [ ] Update refactoring guides
- [ ] Review CONTRACT.md template for language-specific updates

#### Validation
- [ ] Run `mkdocs serve` locally to verify changes
- [ ] Run `mkdocs build --strict` to catch errors
- [ ] Run `uv run python scripts/analyze_code_ratio.py`
- [ ] Run full validation: `docker-compose run --rm validator`
- [ ] Verify all links work: `npx markdown-link-check`
- [ ] Check spelling: `npx cspell "docs/**/*.md"`

#### Release Notes Review
- [ ] Review official release notes for this version
- [ ] Document breaking changes in guide
- [ ] Document new features in guide
- [ ] Update migration guide if major version
- [ ] Add deprecation warnings for removed features

#### Version Table Update
- [ ] Add new version to Supported Versions table
- [ ] Update support status for previous versions
- [ ] Mark EOL versions appropriately
- [ ] Update recommended version badges

### Additional Resources

- **Official release notes**: {language_data.get('url', 'See official documentation')}
- **Migration guide**: Check official documentation
- **Breaking changes**: Review changelog

### Related Issues

Auto-detected by Language Release Tracker (runs monthly on the 1st).

See `.github/workflows/language-tracker.yml` and `scripts/check_language_releases.py`.

---

**Priority**: Medium (unless security/EOL related, then High/Critical)

**Auto-generated by**: Language Release Tracker v1.0.0
"""

    # Create issue via GitHub API
    url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/issues"
    headers = {
        "Authorization": f"token {os.environ['GITHUB_TOKEN']}",
        "Accept": "application/vnd.github.v3+json",
    }

    # Determine labels based on language
    labels = ["type:maintenance", "scope:language-guide", language_data["language"]]

    # Add priority label if EOL is approaching (within 6 months or already passed)
    eol_date = language_data.get("eol_date")
    if eol_date and eol_date != "N/A":
        # If EOL date exists, mark as high priority
        labels.append("priority:high")

    data = {"title": title, "body": body, "labels": labels}

    try:
        response = requests.post(url, headers=headers, json=data, timeout=30)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"Error creating issue: {e}", file=sys.stderr)
        return {}


def main():
    """Main execution function."""
    # Read new_releases from environment
    new_releases_json = os.environ.get("NEW_RELEASES", "[]")

    try:
        new_releases = json.loads(new_releases_json)
    except json.JSONDecodeError as e:
        print(f"Error parsing NEW_RELEASES: {e}", file=sys.stderr)
        return 1

    if not new_releases:
        print("No new releases to process.", file=sys.stderr)
        return 0

    # Extract repo owner and name from environment or git remote
    repo_full = os.environ.get("GITHUB_REPOSITORY", "tydukes/coding-style-guide")
    repo_owner, repo_name = repo_full.split("/")

    created_issues = []
    failed_issues = []

    for release in new_releases:
        print(f"Creating issue for {release['language']}...", file=sys.stderr)
        issue = create_issue(release, repo_owner, repo_name)

        if issue and "html_url" in issue:
            created_issues.append(issue["html_url"])
            print(f"  ✓ Created: {issue['html_url']}", file=sys.stderr)
        else:
            failed_issues.append(release["language"])
            print(
                f"  ✗ Failed to create issue for {release['language']}", file=sys.stderr
            )

    # Summary
    print(f"\n{'='*60}", file=sys.stderr)
    print(
        f"Created {len(created_issues)} issue(s) for new language releases",
        file=sys.stderr,
    )
    if failed_issues:
        print(
            f"Failed to create {len(failed_issues)} issue(s): {', '.join(failed_issues)}",
            file=sys.stderr,
        )
    print(f"{'='*60}", file=sys.stderr)

    for url in created_issues:
        print(f"  - {url}", file=sys.stderr)

    return 0 if not failed_issues else 1


if __name__ == "__main__":
    sys.exit(main())
